---
common:
  site_url: http://example.com
  public_layout: layout
  site_path: /
  use_show_for_resources: false
  exception_notification:
    to_addresses:
    - bobo@example.com
    from_addresss: admin@example.com
  requires_authentication: false
  roles_method: 
  authorized_roles: []
  unsubscribe_path: /listmgr
  dont_include_images_domains:
  - yahoo.com
  - google.com
  - hotmail.com
  - aol.com
  - gmail.com
  - outlook.com
  sleep_time_between_messages: 0.3
  path_prefix: /admin
  table_prefix: mail_manager_
  default_from_email_address: Contact <contact@example.com>
  secret: !binary |-
    NjVkZGRlZWFhNGNhZjA0OGI5NjJmM2Q0M2Y0YzU3
  bounce:
    email_address: bounces@example.com
    login: test
    password: secret
    pop_server: pop.example.com
development:
  site_url: http://example.dev
  secret: !binary |-
    MjI3NzkyMTdjNzk5ZjgzNWU3NThmNTBjYTE1ZWEx
test:
  site_url: http://example.lvh.me:4000
  secret: !binary |-
    ZWIyZTliMGVmOGU1MDlhZTk3NzdmYzNlYmIzNWM4
