---
common:
  site_url: http://example.com
  layout: 'i_reach/application'
  public_layout: layout
  site_path: /
  use_show_for_resources: false
  exception_notification:
    to_addresses:
    - bobo@example.com
    from_addresss: admin@example.com
  requires_authentication: true
  roles_method: role_symbols
  authorized_roles: 
  - admin
  - mail_manager
  unsubscribe_path: /listmgr
  dont_include_images_domains:
  - yahoo.com
  - google.com
  - hotmail.com
  - aol.com
  - gmail.com
  - outlook.com
  sleep_time_between_messages: 0.3
  path_prefix: /admin
  table_prefix: mail_manager_
  default_from_email_address: Contact <contact@example.com>
  secret: <%= ENV['MAIL_MANAGER_SECRET'] %>
  bounce:
    email_address: bounces@lvh.me
    login: test
    password: secret
    pop_server: pop.lvh.me
    port: <%= 
development:
  site_url: http://example.dev
test:
  site_url: http://example.lvh.me:4000
