# this file is used to configure the mail_manager gem
# it works like an older gem called AppConfig
# all environments start with settings from the 'common' section
# and are overridden by the section that matches the environment's name
# also .. if you create a 'config/mail_manager.local.yml' it will override
# what is in 'config/mail_manager.yml' such that you can keep a  version 
# for local settings and not overwrite one that you include in your source control
# also ... these files allow the use of erb syntax to set variables with ruby thus
# allowing ENV variables and such to be used
# here are the valid settings and what they are for:
# site_url: used in various places to get the url of the site (such as in mailings templates)
# public_layout: layout used for public facing pages like unsubscribing and opt-in pages
# layout: layout used for mail manager administratin pages
# site_path: used in case your rails site is at a sub-path of the site url
# exception_notification: (grouping for who gets notified of exceptions)
#   to_addresses: an array of recipients for exceptions
#   from_address: who the exception appears to be from
# requires_authentication: whether the mail manager app requires login
# authorized_roles: array of role names that can administer the mail manager
# roles_method: the method that your "current_user" object defines its role names(returns a list of strings)
# unsubscribe_path: public url for unsubscribing ... this is a prefix and is followed by a message 'guid', defaults to '/listmgr' and routes as '/listmgr/:guid'
# dont_include_images_domains: a list of domains that won't include images in the email, whether or not the mailing is set to include them
# sleep_time_between_messages: a timeout between messages to slow the output of emails to your email server; you should probably limit with your mail server itself if possible
# path_prefix: a prefix to the mail manager routes(defaults to /admin)
# table_prefix: prefixes all mail manager tables with a string to avoid collisions with your app - should be set BEFORE running migrations
# default_from_email_address: where any public messages from the app default to for the "FROM:" header
# secret: a secret for encrypting tokens and guids
# bounce: (a grouping for 'POP' settings for bounce messages and the RETURN_PATH: header)
#   email_address: the account for POPing bounces and RETURN_PATH
#   login: login for account for POPing
#   password: password for account for POPing
#   pop_server: POP server
#   port: PORT of pop server
#   ssl: true/false whether you want to enable ssl for pop
# subscribe_path: public path for double-opt-in 'subscribe' step which sends the email
# honey_pot_field: used to set a field name which will ignore submissions to the subscribe action if filled
# double_opt_in_path: path to route the double-opt-in confirmation action to
# signup_email_address: email address for the FROM: of a double opt in/subscribe email
#
# The following 2 might be deprecated soon
# show_title: can be used in templates/layouts to see whether you should show a title
# use_show_for_resources: whether to have links to "show" actions - we don't use them really in this app..
# and the 'show' actions aren't really currently supported
#
---
common:
  site_url: http://example.com
  public_layout: mail_manager/layout
  site_path: "/"
  use_show_for_resources: false
  exception_notification:
    to_addresses:
    - bobo@example.com
    from_address: Mail Manager Exception <admin@example.com>
  requires_authentication: true
  roles_method: role_symbols
  authorized_roles:
  - admin
  - mail_manager
  unsubscribe_path: "/listmgr"
  subscribe_path: "/listmgr/subscribe"
  subscribe_thank_you_path: "/listmgr/subscribe_thank_you"
  double_opt_in_path: "/listmgr/confirm"
  honey_pot_field: company_name
  signup_email_address: Register <signup@example.com>
  dont_include_images_domains:
  - yahoo.com
  - google.com
  - hotmail.com
  - aol.com
  - gmail.com
  - outlook.com
  sleep_time_between_messages: 0.3
  path_prefix: "/admin"
  table_prefix: mail_manager_
  default_from_email_address: Contact <contact@example.com>
  secret: "<%= ENV['MAIL_MANAGER_SECRET'] %>"
  bounce:
    email_address: bounces@lvh.me
    login: test
    password: secret
    pop_server: pop.lvh.me
    port: 110
  layout: i_reach/application
development:
  site_url: http://example.dev
  secret: 9ddaeac4a0c6a1540ee4312ef7b8da
test:
  site_url: http://example.lvh.me:4000
  secret: e5fca98d93481707d99b419fd9ffde
