# this file is used to configure the newsletter gem
# it works like an older gem called AppConfig
# all environments start with settings from the 'common' section
# and are overridden by the section that matches the environment's name
# also .. if you create a 'config/newsletter.local.yml' it will override
# what is in 'config/newsletter.yml' such that you can keep a  version 
# for local settings and not overwrite one that you include in your source control
# also ... these files allow the use of erb syntax to set variables with ruby thus
# allowing ENV variables and such to be used
# here are the valid settings and what they are for:
# site_url: used in various places to get the url of the site (such as in mailings templates)
# site_path: used in various places to get the url of the site (such as in mailings templates)
# layout: layout used for newsletter administration pages
# archive_layout: layout used for public facing pages like the newsletter archive
# designs_require_authentication: whether you need to log in to manage designs(recommended)
# design_authorized_roles: array of role names that can manage designs
# newsletters_require_authentication: whether you need to log in to manage newsletters(everyone can currently see them.. devise your own abilities if you want to require login for these)
# newsletter_authorized_roles: array of role names that can manage newsletters
# roles_method: the method which gives a list of role names for the 'current_user' of the app, if it answers with an array of names as strings with 'roles' or a string with 'role' this doesn't have to be set
# designs_path: path from your rails root where design templates are saved
# asset_path: where your newsletter assets are saved(images, pdfs, etc for newsletter instances-uploaded with carrier_wave)
# table_prefix: prefix your newsletter tables to avoid collisions
#
#
# The following 2 might be deprecated soon
# show_title: can be used in templates/layouts to see whether you should show a title
# use_show_for_resources: whether to have links to "show" actions - we don't use them really in this app..
# and the 'show' actions aren't really currently supported
---
common:
  site_url: http://texashearingaids.org
  layout: i_reach/application
  archive_layout: main_layout
  use_show_for_resources: false
  show_title: true
  designs_require_authentication: true
  design_authorized_roles:
  - designer
  - admin
  newsletters_require_authentication: true
  newsletter_authorized_roles:
  - newsletter
  - admin
  roles_method: role_symbols
  designs_path: "<%= File.join(Rails.root,'newsletters') %>"
  asset_path: newsletter_assets
  site_path: "/admin"
  table_prefix: newsletter
  path_prefix: "/admin"
demo:
  site_url: http://test-thaa.lnstar.com
development:
  site_url: http://ireach.dev
test:
  site_url: http://ireach.lvh.me
